apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vzhao0504/argocd.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: alto-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true