apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: alto
  labels:
    app: java-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: rslim087/kubernetes-course-grade-submission-api:stateless
        ports:
          - containerPort: 3000
